### PR TITLE
Style admin

### PR DESCRIPTION
**Pull request by Swiip**
Full redesign of the backo 🎉 

With styled-components 🎉 

Not everything is fully operational but it's clearly a new start.

### CODE REVIEW

**Comment by Slashgear** [comment]
Your svg files seem to have useless `g` tags, they may need to be cleaned ?

**Comment by Swiip** [comment]
@Slashgear in fact, all svg are useless we could remove them, I only use optimized jsx version in Icon.js

**Comment by Swiip** [comment]
💀 💱 💣  components.js... :(

**Comment by Swiip** [comment]
Removed unused icons : +5,085 −4,841 is better ^^

**Pull request merged**
